stop:
	cp ./stop_wait/client.py ./loss
	cp ./stop_wait/client.py ./no_loss
	cp ./stop_wait/server.py ./loss
	cp ./stop_wait/server.py ./no_loss
	cp rdt_lib.py ./loss
	cp rdt_lib.py ./no_loss

pipeline:
	cp ./pipelined/client.py ./loss
	cp ./pipelined/client.py ./no_loss
	cp ./pipelined/server.py ./loss
	cp ./pipelined/server.py ./no_loss
	cp rdt_lib.py ./loss
	cp rdt_lib.py ./no_loss
